export const GET_CASTS_LIST_REQ = "GET_CASTS_LIST_REQ"
export const GET_CASTS_LIST_SUCCESS = 'GET_CASTS_LIST_SUCCESS'
export const GET_CASTS_LIST_FAIL = 'GET_CASTS_LIST_FAILURE'
export const CREATE_CAST_REQ = 'CREATE_CAST_REQ'
export const CREATE_CAST_SUCCESS = 'CREATE_CAST_SUCCESS'
export const CREATE_CAST_FAIL = 'CREATE_CAST_FAIL'