export const MOVIE_LIST_REQ = 'MOVIE_LIST_REQ'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'
export const MOVIE_SINGLE_REQ= "MOVIE_SINGLE_REQ"
export const MOVIE_SINGLE_SUCCESS = "MOVIE_SINGLE_SUCCESS"
export const MOVIE_SINGLE_FAIL = "MOVIE_SINGLE_FAIL"